"""update

Revision ID: 7551d2e61e1a
Revises: 6b9fc30d5e7d
Create Date: 2025-08-17 00:28:31.796079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7551d2e61e1a'
down_revision: Union[str, None] = '6b9fc30d5e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decks', 'updated_at', server_default=sa.func.now())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decks', 'updated_at', server_default=None)
    # ### end Alembic commands ###
