"""Add server default to card updated_at

Revision ID: 89f330b6779d
Revises: 7551d2e61e1a
Create Date: 2025-08-17 01:01:11.492402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f330b6779d'
down_revision: Union[str, None] = '7551d2e61e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
